QTURL: http://192.168.1.249:8984/hk-financial-services/index.html #测试
#URL: http://39.105.87.46:8501/hk-management-services/login.html?_v=20180525targetUrlAfterLogin=http://39.105.87.46:8501/hk-management-services/index.html
#URL: http://192.168.1.249:8486/hk-management-services/login.html
HTURL: http://192.168.1.249:8984/hk-management-services/login.html?_v=20180525&targetUrlAfterLogin=http://192.168.1.249:8984/hk-management-services/index.html
JKURL: http://192.168.1.249:8984
HOST: 192.168.1.250
PORT: 3306
user: dev_db_user
password: yrSuper001
db: finance_hkjf
charset: 'utf8mb4'
log:
    file_name: test.log
    backup: 5
    console_level: WARNING
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


